server:
    port: 8096
    servlet:
      context-path: /api 
spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_db:3306/java_to_dev_app_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect

logging:
  level:
    org.springframework.ws: DEBUG
    org.apache.http: ERROR
    javax.net: ERROR
    sun.security.ssl: DEBUG
    sun.net: ERROR   
    com.todotask: TRACE 
    org.springframework.web: DEBUG
    java.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE   
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.apache.http.wire: ERROR

